version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: chessdb_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chessdb
      MYSQL_USER: chessuser
      MYSQL_PASSWORD: chesspass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
